import { createUseStyles } from 'react-jss'
import BANNER_URL from '../helper/BannerUrl'
interface InterfaceBanner {
  [key: string]: {}
}
const bannerData: InterfaceBanner = {
  'chennai-super-kings-banner': {
    backgroundImage: `url(${BANNER_URL['chennai-super-kings'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#0081e5 60%,#005699)',
    },
  },
  'chennai-super-kings-overlay-image': {
    backgroundImage: `url(${BANNER_URL['chennai-super-kings'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'chennai-super-kings-overlay': {
    background: '#fdb913a1',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'delhi-capitals-banner': {
    backgroundImage: `url(${BANNER_URL['delhi-capitals'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#f83430 60%,#d40b07)',
    },
  },
  'delhi-capitals-overlay-image': {
    backgroundImage: `url(${BANNER_URL['delhi-capitals'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'delhi-capitals-overlay': {
    background: '#004c93b3',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'kings-xi-punjab-banner': {
    backgroundImage: `url(${BANNER_URL['kings-xi-punjab'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#c7c8ca 60%,#a0a1a5)',
    },
  },
  'kings-xi-punjab-overlay-image': {
    backgroundImage: `url(${BANNER_URL['kings-xi-punjab'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'kings-xi-punjab-overlay': {
    background: '#b3252482',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'kolkata-knight-riders-banner': {
    backgroundImage: `url(${BANNER_URL['kolkata-knight-riders'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#efb04c 60%,#db8e14)',
    },
  },
  'kolkata-knight-riders-overlay-image': {
    backgroundImage: `url(${BANNER_URL['kolkata-knight-riders'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'kolkata-knight-riders-overlay': {
    background: '#3d2256cc',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'mumbai-indians-banner': {
    backgroundImage: `url(${BANNER_URL['mumbai-indians'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#aa9a7f 60%,#857458)',
    },
  },
  'mumbai-indians-overlay-image': {
    backgroundImage: `url(${BANNER_URL['mumbai-indians'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'mumbai-indians-overlay': {
    background: '#005ea0b5',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'rajasthan-royals-banner': {
    backgroundImage: `url(${BANNER_URL['rajasthan-royals'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#d5ab4b 60%,#ab8328)',
    },
  },
  'rajasthan-royals-overlay-image': {
    backgroundImage: `url(${BANNER_URL['rajasthan-royals'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'rajasthan-royals-overlay': {
    background: '#004b8cb5',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'royal-challengers-bangalore-banner': {
    backgroundImage: `url(${BANNER_URL['royal-challengers-bangalore'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#ff3245 60%,#e50015)',
    },
  },
  'royal-challengers-bangalore-overlay-image': {
    backgroundImage: `url(${BANNER_URL['royal-challengers-bangalore'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'royal-challengers-bangalore-overlay': {
    background: '#000000b8',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
  'sunrisers-hyderabad-banner': {
    backgroundImage: `url(${BANNER_URL['sunrisers-hyderabad'].imagehuddle.default})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: '100% 0',
    backgroundSize: 'auto 100%',
    position: 'relative',
    height: '460px',
    '&::after': {
      bottom: '0',
      content: "''",
      clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
      left: '0',
      position: 'absolute',
      width: '63%',
      top: '0',
      background: 'linear-gradient(#fdb913 60%,#c28a02)',
    },
  },
  'sunrisers-hyderabad-overlay-image': {
    backgroundImage: `url(${BANNER_URL['sunrisers-hyderabad'].image.default})`,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    bottom: '0',
    clipPath: 'polygon(0 0,93% 0,100% 100%,0 100%)',
    position: 'absolute',
    left: '0',
    top: '0',
    width: '60%',
    zIndex: '5',
  },
  'sunrisers-hyderabad-overlay': {
    background: '#fb653fb8',
    bottom: '0',
    content: '',
    clipPath: 'polygon(0 0,90.1% 0,100% 100%,0 100%)',
    left: '0',
    position: 'absolute',
    width: '105%',
    top: '0',
  },
}
const BANNER_STYLE = createUseStyles(bannerData)
export default BANNER_STYLE
